### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by toranb** [alexspeller/ember-cli-active-link-wrapper#1]
Just wanted to verify this was simply a cleaner/nicer way of writing the below (and that the below isn't going away)

``` js
        {{#link-to 'foo' tagName="li"}}
            <a {{bind-attr href="view.href"}}>details</a>
        {{/link-to}}
```

**Comment by alexspeller** [comment]
As far as I can tell that doesn't work:

http://jsfiddle.net/alexspeller/w3sj0mkt/5/

The link ends up with no href.

Also it's semantically different. Note in your example clicking anywhere on the li ends up activating the link, which may not be what you want. If you are using bootstrap for example, the LI is not assumed be clickable.

**Comment by toranb** [comment]
Ah thanks for the clarification @alexspeller 

also -thanks for throwing up the jsfiddle :)
