### ISSUE TITLE
Proposed changes, and how to structure PR's

### ISSUE THREAD

**Issue by Panman82** [alexspeller/ember-cli-active-link-wrapper#10]
I have a few proposed changes to submit but don't know how to structure the PR's. The main point of contention is moving main functionality to a Mixin. But here are my proposed changes;
1. Move main functionality to a Mixin, that way this could be use in other addon components that might already provide a dropdown component
2. Enable changing of the active class name, to solve issue #3 
3. Add in a "disabled" state/class when ALL child links are also disabled
4. Enable changing of the link jQuery selector, in case `{{link-to}}` tagName is changed
5. Move the `childLinkViews` build code out of `didRender`, apparently there are questions on how hooks are ran when defined in a Mixin but overridden in the Component (more research needed)
6. Move away from the "active" property name, causes problems when used with other addon components (at least it did for me)

Here is a gist of my proposed changes for review. Again, I'll submit PR's after some discussion and best approach for PR structure.

https://gist.github.com/Panman8201/ddb4be922143d9681078

**Comment by Panman82** [comment]
I've created a fork / branch with the changes for review. Looking for some discussion on these proposed changes. Will submit the PR once things are approved. Thanks!

https://github.com/Panman8201/ember-cli-active-link-wrapper/tree/proposed-changes

**Comment by Panman82** [comment]
@alexspeller did you have any thoughts on these changes? Thanks!

**Comment by alexspeller** [comment]
Hi @Panman8201 thanks for looking at these - I have been avoiding coding over the holidays but I promise I will look at this within 24hours and get a proper response :)

**Comment by Panman82** [comment]
@alexspeller Same here, figured I wouldn't bug ya over the holidays. No big hurry, just "back to work Monday" and following up with my todo's. Thanks!

**Comment by alexspeller** [comment]
> Move main functionality to a Mixin, that way this could be use in other addon components that might already provide a dropdown component

Seems good to me

> Enable changing of the active class name, to solve issue #3 

My hesitance with this is that I think the active class should be pulled from the `link-to` itself, so that it's not set in two places

> Add in a "disabled" state/class when ALL child links are also disabled

Looks good

> Enable changing of the link jQuery selector, in case `{{link-to}}` tagName is changed

The whole fact that this is even _using_ a jQuery selector is a terrible hack in the first place, which I was kind of hoping to keep hidden away and not make part of the public api. That said, this change is so minimal to implement that blocking it on principle seems pointless ;)

> Move the `childLinkViews` build code out of `didRender`, apparently there are questions on how hooks are ran when defined in a Mixin but overridden in the Component (more research needed)

If this is going to be used as a mixin instead of just a simple component, it should probably use an event instead; `Ember.on('didRender, …)`

> Move away from the "active" property name, causes problems when used with other addon components (at least it did for me)

Fine but property names should not end in `Binding` as [this has special meaning in ember](https://ember-twiddle.com/915a6d4526a4068ff9ae)

**Comment by Panman82** [comment]
> My hesitance with this is that I think the active class should be pulled from the link-to itself, so that it's not set in two places

That's an interesting idea. What about having `activeClass` be a computed property for that case, but would still remain "overrideable" (which I actually need to do in a few places). What would you expect to happen if multiple child `{{link-to}}`'s are active? Unlikely but possible, such as in a drop-down.

> The whole fact that this is even using a jQuery selector is a terrible hack in the first place, which I was kind of hoping to keep hidden away and not make part of the public api. That said, this change is so minimal to implement that blocking it on principle seems pointless ;)

Agreed, would rather not need it but figured some folks might use a `<button>` or such instead...

> If this is going to be used as a mixin instead of just a simple component, it should probably use an event instead; Ember.on('didRender, …)

As for `didRender` hook vs evented, I was going off of the "[Proper use of Ember on()](http://notmessenger.com/proper-use-of-ember-on/)" article and I know Stefan Penner said the evented version is less performant than the actual hook. In the end both will work, your call...

> Fine but property names should not end in Binding as this has special meaning in ember

Huh, I forgot that was possible. I'll refactor it away from using "Binding".

**Comment by alexspeller** [comment]
> That's an interesting idea. What about having activeClass be a computed property for that case, but would still remain "overrideable" (which I actually need to do in a few places). What would you expect to happen if multiple child {{link-to}}'s are active? Unlikely but possible, such as in a drop-down.

I haven't really thought about the multiple case - in every case I use this only one sub-link can be active. I guess the best thing to do is take it from the first one and allow it to be overridable

> As for didRender hook vs evented, I was going off of the "Proper use of Ember on()" article and I know Stefan Penner said the evented version is less performant than the actual hook. In the end both will work, your call...

From that page:

> The very rare exception
> 
> The only time to consider using on() is if the execution order of your functions definitely does not matter AND you're in a situation in which you need the behavior to not break if _super() is not called by extending code, such as in a mixin provided by an addon.

That's us :)

**Comment by Panman82** [comment]
I'll work on these changes and submit a PR. Would you like these features as separate commits, like my [`proposed-changes` branch](https://github.com/Panman8201/ember-cli-active-link-wrapper/commits/proposed-changes)? Or just lump them into one? Something else?

**Comment by alexspeller** [comment]
seperate PRs is best I think - that way one thing won’t hold up anything
else. Thanks!

**Comment by Panman82** [comment]
Humm..., I'm not sure how to structure separate PRs without conflicts between them. I was kind of hoping to get the go-ahead for everything first and submit one PR with multiple commits. :grin:

**Comment by alexspeller** [comment]
One PR is also fine in that case - I don't really care that much about the git structuring etc as long as it all makes sense
