### ISSUE TITLE
Ember 2.8.0-beta.1 viewRegistry error

### ISSUE THREAD

**Issue by Panman82** [alexspeller/ember-cli-active-link-wrapper#17]
I'm getting an "Uncaught TypeError: Cannot read property 'ember1054' of undefined" error from [`this._viewRegistry[view.id]` here](https://github.com/alexspeller/ember-cli-active-link-wrapper/blob/bcbf86ca8b17555a16f03341779f6a667429bbf7/addon/mixins/active-link.js#L22) when upgrading to ember 2.8.0-beta.1. Downgrading to ember 2.7.0 removes this problem, so it's probably an underlying ember.js bug.

**Comment by Panman82** [comment]
Ran all tests locally, `ember try:testall` and the ember-beta and ember-canary scenarios both failed. Ember-1-13 and ember-release both succeed.

**Comment by alexspeller** [comment]
I'm guessing it's because I'm abusing private api to make this work :)

**Comment by broerse** [comment]
It now fails in production on ember-cli 2.8.0 not beta.

**Comment by broerse** [comment]
Perhaps fix with something like this?

https://github.com/emberjs/ember-inspector/blob/ddde4b19abeff6dde141815f32aa28a679a7b6d8/ember_debug/view-debug.js#L619

**Comment by Robdel12** [comment]
If you're willing to drop support for anything lower than 2.3 I can drop a PR now that fixes it. It'll use `getOwner`.

**Comment by alexspeller** [comment]
@Robdel12 that'd be awesome, I can bump major version and put a note in the readme.

**Comment by Robdel12** [comment]
Actually I might hold off, it's still breaking in beta & canary. It might be unrelated though.

**Comment by broerse** [comment]
@Robdel12 we can also add a 2.3 version check like this:

https://github.com/mharris717/ember-cli-pagination/blob/master/index.js#L7

**Comment by dfreeman** [comment]
@Robdel12 You could also use `ember-getowner-polyfill` to maintain pre-2.3 support

**Comment by alexspeller** [comment]
This should now be fixed by version `0.3.0`, please let me know if any further issues
