### ISSUE TITLE
Error in Fastboot on 0.3.0

### ISSUE THREAD

**Issue by bakerac4** [alexspeller/ember-cli-active-link-wrapper#19]
```
There was an error running your app in fastboot. More info about the error: 
 TypeError: Cannot read property 'lookup' of undefined
```

Seems to come from [this line](https://github.com/alexspeller/ember-cli-active-link-wrapper/blob/master/addon/mixins/active-link.js#L23)

Fastboot: 1.0.0-beta.9
Ember: 2.8.1

I think the fix for this might be to use didInsertElement to schedule the afterRender event?

**Comment by alexspeller** [comment]
@bakerac4 all tests pass if I change this [`didReceiveAttrs`](https://github.com/alexspeller/ember-cli-active-link-wrapper/blob/master/addon/mixins/active-link.js#L18) to `didInsertElement` - if you try that, does it solve the fastboot issue?

**Comment by bakerac4** [comment]
Sorry for the late reply, but yea that does fix it. It seems that #21 fixes this issue so I'll close. Thanks for the quick merge!
