### ISSUE TITLE
Ember 2.10 compatibility?

### ISSUE THREAD

**Issue by kernel-io** [alexspeller/ember-cli-active-link-wrapper#24]
I have just updated an application to Ember 2.10. Switching between routes I now get this error

Assertion Failed: You modified routeHierarchy twice on <vendormax-6@component:bread-crumbs::ember649> in a single render. This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.

at the moment it is saying the breadcrumbs are the issue, but it flicks around with different components and different properties each time.

The error goes away completely if I remove all the `active-links` from the page, I know this is a truly unscientific way of testing but its the best I can do while poking around in the dark. I could create a test application for you?

**Comment by alexspeller** [comment]
Huh that's weird - test app would be great, thanks

**Comment by kernel-io** [comment]
I was just updating my original post, I found that the error is because I have a wormhole within an active-link. I think I will have to refactor.

by the way, you're fast! 😍 

I think this comment is related, I'm taking that views inside the active-link are regenerated each time. 
https://github.com/yapplabs/ember-wormhole/issues/3#issuecomment-102943802

Time to implement a service to share the data between the two places so I don't need to wormhole it

**Comment by Turbo87** [comment]
FWIW I just hit `Assertion Failed: You modified _transitioningIn twice on <skylines@component:active-link::ember709> in a single render.` when switching translations multiple times on my app.
