### ISSUE TITLE
Ember 3.x compatibility

### ISSUE THREAD

**Issue by engwan** [alexspeller/ember-cli-active-link-wrapper#28]
After upgrading to latest Ember 3.4, I'm getting:

    Could not find module `ember` imported from `ember-cli-active-link-wrapper/components/active-link`

Seems like `import Ember from 'ember'` is no longer supported.

**Comment by nickschot** [comment]
@engwan you can temporarily resolve this by adding back [ember-cli-shims](https://github.com/ember-cli/ember-cli-shims) into your package.json.

**Comment by alexspeller** [comment]
Fixed with v0.5.0
