### ISSUE TITLE
Changing active class

### ISSUE THREAD

**Issue by oskarrough** [alexspeller/ember-cli-active-link-wrapper#3]
Hi, thanks for this small helper. It's great. Would it be possible for it to take the default activeClass?

We normally change `active` to `is-active` in our apps.

``` JavaScript
Ember.LinkView.reopen({
    activeClass: 'is-active'
});
```

**Comment by drewchandler** [comment]
You can do this for now: 

app/components/active-link.js
```javascript 
import ActiveLink from 'ember-cli-active-link-wrapper/components/active-link';

export default ActiveLink.extend({
  classNameBindings: ['active:is-active']
});
```

**Comment by alexspeller** [comment]
I think this makes sense, I'd be happy to accept a PR that did this
