### ISSUE TITLE
1.13+ Support

### ISSUE THREAD

**Issue by rwjblue** [alexspeller/ember-cli-active-link-wrapper#4]
In 1.13.0-beta.1 and above, the `childViews` array is not maintained (HTMLBars maintains a tree structure instead of a flat array listing).

I spiked getting things working for both pre-1.13 and post in [this JSBin](http://emberjs.jsbin.com/rwjblue/553/edit), snippet below:

``` javascript
  didRender: function() { 
    function filterAttrMorphs(node) {
      return node.constructor.name !== 'AttrMorph';
    }
    var childViews = this._renderNode.childNodes.filter(filterAttrMorphs)[0].childNodes
    .map(function(node) {
      return node.emberView;
    });

    this.set('childViews', Ember.A(childViews));
  }
```

I am not super happy with the requirement to use the private `_renderNodes`, and will be trying to get something working in core for later betas, but figured folks might want to use this addon against 1.13+ in the interim.

I'll try to do an actual PR later and add testing for cross Ember versions.

**Comment by raytiley** [comment]
:+1:

**Comment by lstyles** [comment]
The JSBin linked doesn't work for me in IE 11. 

I get this error:

```
TypeError: Unable to get property 'map' of undefined or null reference
   at didRender (http://emberjs.jsbin.com/rwjblue/553:78:5)
   at trigger (http://builds.emberjs.com/canary/ember.debug.js:41111:9)
   at superWrapper (http://builds.emberjs.com/canary/ember.debug.js:19570:9)
   at Renderer.prototype.didRender (http://builds.emberjs.com/canary/ember.debug.js:11003:7)
   at Renderer_dispatchLifecycleHooks (http://builds.emberjs.com/canary/ember.debug.js:10916:7)
   at Renderer_renderTopLevelView (http://builds.emberjs.com/canary/ember.debug.js:10882:7)
   at Queue.prototype.invokeWithOnError (http://builds.emberjs.com/canary/ember.debug.js:885:13)
   at Queue.prototype.flush (http://builds.emberjs.com/canary/ember.debug.js:943:13)
   at DeferredActionQueues.prototype.flush (http://builds.emberjs.com/canary/ember.debug.js:748:13)
   at Backburner.prototype.end (http://builds.emberjs.com/canary/ember.debug.js:173:11)
```

**Comment by raytiley** [comment]
Just a note for anyone trying to manually patch this. You can't rely on the name of `AttrMorph` in production builds.  I changed the code as follows:

``` js
function filterAttrMorphs(node) {
  return node.attrName === undefined;
}
```

This seems to work with production builds. I know @rwjblue is planning on adding a brand to `AttrMorph` so it can be detected more cleanly.

**Comment by justinko** [comment]
Had to use this variation with 1.13.0:

``` javascript
  didRender: function() {
    function filterAttrMorphs(node) {
      return node.attrName === undefined;
    }
    var childViews = this._renderNode.childNodes.filter(filterAttrMorphs)[0].childNodes.map(function(node) {
      return node.childNodes[0].emberView;
    });
    this.set('childViews', Ember.A(childViews));
  }
```

**Comment by alexlafroscia** [comment]
Seems to have changed in 1.13.2, @justinko's solution doesn't seem to work for me.

**Comment by Panman82** [comment]
Ug, I can't get this to work either. Except I was getting junk in the second set of `childNodes` that don't have an `emberView`, which causes a "Cannot call get with 'active' on an undefined object." error. Had to make a filter to get rid of those, but it still doesn't work right. Any updates / ideas on this @rwjblue or @raytiley ? I'm on ember 1.13.4 using ember-cli 1.13.1. Here is my `didRender` hook:

```
didRender: function() {
    function filterAttrMorphs(node) {
        return node.attrName === undefined;
    }
    function filterNullEmberViews(node) {
        return !!node.emberView;
    }
    function mapEmberViews(node) {
        return node.emberView;
    }
    var childViews = this._renderNode.childNodes.filter(filterAttrMorphs)[0].childNodes.filter(filterNullEmberViews).map(mapEmberViews);
    this.set('childViews', Ember.A(childViews));
}
```

**Comment by miguelcobain** [comment]
I'd like to add another alternative:

``` hbs
{{#link-to "dashboard" tagName="li" href=false}}
  {{#link-to "dashboard" bubbles=false}}
    Dashboard
  {{/link-to}}
{{/link-to}}
```

**Comment by Panman82** [comment]
@miguelcobain I don't think that'll work if it's a drop-down component where there may be multiple `{{link-to}}`s going to different paths. Also, the root container (this component) should not trigger a transition event. My specific use case here is for bootstraps navbar and dropdowns.

**Comment by miguelcobain** [comment]
That works for whenever you need an `<li>` with an active class when the given route is active. I'm also using bootstrap. I don't know why it wouldn't work with navbars. I'm using them with this. :/

**Comment by elidupuis** [comment]
Any movement here? I just came across this issue in our app...

**Comment by maartenparmentier** [comment]
I also would love to hear the progression..

**Comment by alexspeller** [comment]
@rwjblue I have taken a more… _brute force_ approach in `0.0.4` - it seems to work though.

**Comment by alexspeller** [comment]
@rwjblue https://github.com/alexspeller/ember-cli-active-link-wrapper/blob/master/addon/components/active-link.js#L12-L21
